### ISSUE TITLE
lib/index.js is missing in the published package

### ISSUE THREAD

**Issue by hakatashi** [sequelize/umzug#138]
```
$ yarn list umzug
yarn list v0.20.3
├─ sequelize-cli@2.7.0
│  └─ umzug@1.12.0
└─ umzug@2.0.0
Done in 1.79s.

$ ls node_modules/umzug
CHANGELOG.md  LICENSE  README.md  gulpfile.js  node_modules  package.json  src  test  yarn.lock

$ node
> const umzug = require('umzug')
Error: Cannot find module 'umzug'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at repl:1:14
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:336:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:533:10)
>
```

Related: https://github.com/tsg-ut/mnemo/pull/272

**Comment by hakatashi** [comment]
2.0.1 seems to work well. Thanks!

**Comment by jukkah** [comment]
Yeah, that build was broken. Thanks for reporting. :+1:
