### ISSUE TITLE
Catching Umzug errors with async/await

### ISSUE THREAD

**Issue by nadavoosh** [sequelize/umzug#154]
I'm using async/await syntax to run my migrations:
```
try {
    await umzug.up();
  } catch (error) {
    throw new Error(`Migration Error: ${error}`);
  }
```
I can't seem to get the `catch` block to hit. When I write a failing migration, I just see:

```
Unhandled rejection SequelizeDatabaseError: column "testingMigrations" of relation "users" does not exist
    at Query.formatError (/Users/nadav/dev/approvals/server/node_modules/sequelize/lib/dialects/postgres/query.js:351:16)
    at query.catch.err (/Users/nadav/dev/approvals/server/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/nadav/dev/approvals/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```

And my code keeps on executing. I'd like for it to fail hard if the migrations fail.  Am I missing something obvious? Thanks!

**Comment by nadavoosh** [comment]
Oh -- got it, I need to ensure that the migrations always return the promise, or else the above happens.
