### ISSUE TITLE
Docs: add webpack guidance (users see "Error: Cannot find the module")

### ISSUE THREAD

**Issue by amaranadh-wal** [sequelize/umzug#187]
Hi Team, 
I have following issue when I am using umzug with Electronjs with sqlite database.

Error: Cannot find module 'C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\migrations\20181119091008-create-language.js'

But the file is available in the location. I do not understand why it is happening. 

The complete stack trace is below.

 **Cannot find module 'C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\migrations\20181119091008-create-language.js'
  
  at r (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib sync:6:40)
    
at e.exports.migration (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\migration.js:99:1)
    
at C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\migration.js:128:1
   
at Generator.next (<anonymous>)
    at value (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:27:1)
    at exports (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\babel-runtime\helpers\extends.js:3:1)
    at new undefined (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\core-js\library\modules\es6.promise.js:185:1)
    at C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\babel-runtime\helpers\asyncToGenerator.js:21:1
    at e.exports.defineProperty [as _exec] (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\storages\JSONStorage.js:3:1)
    at e.exports.downName [as up] (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\migration.js:99:1)
    at e.exports.unlogMigration (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\index.js:158:1)
From previous event:
    at resolve (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\index.js:135:1)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at i.default.map.then.then.e (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\index.js:133:1)
From previous event:
    at e.exports.migration [as execute] (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\node_modules\umzug\lib\index.js:131:1)
    at e.exports.<anonymous> (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\app\main.dev.js:117:16)
From previous event:
    at App.migrations (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\app\main.dev.js:116:55)
    at Generator.next (<anonymous>)
    at n (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\app\main.dev.js:16:1)
    at sequelize (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\app\main.dev.js:18:37)
    at new Promise (<anonymous>)
    at App.<anonymous> (C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate\resources\app.asar\webpack:\app\main.dev.js:16:1)
    at App.emit (events.js:187:15)

[2019-01-08 16:16:54.020] [info] {"code":"MODULE_NOT_FOUND"}
**

**Comment by Sean-214** [comment]
Because webpack.

```js
const umzug = new Umzug({
    ......
    migrations: {
        ......
        customResolver: function (filePath) {
            return __non_webpack_require__(filePath);
        },
        ......
    },
    ......
});
```

**Comment by inf265** [comment]
I did that on a version tag. Ok we start from the beginnig: I checkout out current master from today and tried to start spacedeck:

fmetz@minka:~/spacedeck-open$ node spacedeck.js 
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'umzug'
Require stack:
- /home/fmetz/spacedeck-open/models/db.js
- /home/fmetz/spacedeck-open/spacedeck.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/fmetz/spacedeck-open/models/db.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/fmetz/spacedeck-open/models/db.js',
    '/home/fmetz/spacedeck-open/spacedeck.js'
  ]
}
fmetz@minka:~/spacedeck-open$ git pull
Already up-to-date.
fmetz@minka:~/spacedeck-open$ node --version
v13.11.0
fmetz@minka:~/spacedeck-open$
