### ISSUE TITLE
Test failed due to timeout

### ISSUE THREAD

**Issue by papb** [sequelize/umzug#224]
@mmkal When trying to publish a new version, this happened:

```
× Command failed with exit code 1: npm test
PASS test/test.ts (5.886s)
PASS test/Umzug/down.test.js (8.651s)
PASS test/Umzug/execute.test.js
PASS test/storage/sequelize.test.ts (12.31s)
PASS test/storage/mongodb.test.ts
PASS test/storage/json.test.ts
PASS test/Umzug/up.test.js
PASS test/Umzug/executed.test.js
PASS test/storage/memory.test.ts
PASS test/Umzug/pending.test.js
PASS test/Umzug/constructor.test.js
PASS test/Umzug/migrationsList.test.js
FAIL test/fixtures/index.test.ts (14.974s)
  ● custom resolver › resolves javascript files if no custom resolver is defined

    : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:

      57 |      });
      58 |
    > 59 |      it('resolves javascript files if no custom resolver is defined', async () => {
         |      ^
      60 |              state.pattern = /\.js$/;
      61 |              state.path = resolve(__dirname, 'javascript');
      62 |              state.customResolver = undefined;

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/fixtures/index.test.ts:59:2)
      at Object.<anonymous> (test/fixtures/index.test.ts:12:1)

Test Suites: 1 failed, 12 passed, 13 total
Tests:       1 failed, 204 passed, 205 total
Snapshots:   4 passed, 4 total
Time:        22.412s, estimated 35s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Can we increase the timeout for all tests?

**Comment by mmkal** [comment]
@papb I haven't seen this since you opened - does it still happen for you?

**Comment by papb** [comment]
Hmmm I didn't try to publish again... But I recall that when this happened I ended up simply retrying and it worked. This can be closed for now I think
