### ISSUE TITLE
Migrations with sequelize and enums

### ISSUE THREAD

**Issue by lededje** [sequelize/umzug#544]
An issue that appears when using umuz and sequelize when you have enums in your migrations and models.

```
"dependencies": {
    "pg": "^8.7.3",
    "pg-hstore": "^2.3.4",
    "sequelize": "^6.17.0",
    "umzug": "^3.0.0"
  }
```

Minimum viable example: https://github.com/lededje/migration-bug

```
docker-compose up
node index.ts
```

expected result: Migrations are run up and then down

actual result: 

```
➜  test git:(main) node index                     
{ event: 'reverting', name: '0001-create-tags' }  
                                                  
/home/lededje/repos/test/node_modules/umzug/lib/umzug.js:205
                    throw new MigrationError({ direction: 'down', ...params }, e);
                          ^                       
MigrationError: Migration 0001-create-tags (down) failed: Original error: Cannot set properties of un
defined (setting 'supportsSearchPath')       
    at /home/lededje/repos/test/node_modules/umzug/lib/umzug.js:205:27                               
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Umzug.runCommand (/home/lededje/repos/test/node_modules/umzug/lib/umzug.js:110:20)
    at async /home/lededje/repos/test/index.js:76:3 {
  jse_shortmsg: 'Migration 0001-create-tags (down) failed',
  jse_cause: VError: Original error: Cannot set properties of undefined (setting 'supportsSearchPath'
)                                                 
```
If you checkout the `working` branch, and repeat the test (with a clean db) the migrations run as expected.

**Comment by mmkal** [comment]
A note in the docs about this would be very welcome. Umzug isn’t coupled to sequelize so if you use sequelize you need to be aware about how it caches models etc.
