### ISSUE TITLE
Issue with identifying migration files as input to umzug instance

### ISSUE THREAD

**Issue by pavansandeep2910** [sequelize/umzug#611]
### Discussed in https://github.com/sequelize/umzug/discussions/610

<div type='discussions-op-text'>

<sup>Originally posted by **pavansandeep2910** July  3, 2023</sup>
In my application, I am bundling my src code into a single file(using Webpack for this) which includes migration code too because I want to run the migrations with the help of an API. I created the Umzug instance below like this 

`new Umzug({
    migrations: {
      glob: ['migrations/test-migration.js'],
    },
    context: queryInterface,
  });`

But Umzug is not able to identify the migrations file. so, in the Webpack config file, I included this option `node: {__dirname: true}` and changed the above code as below

`new Umzug({
    migrations: {
      glob: ['migrations/test-migration.js', {cwd: __dirname}],
    },
    context: queryInterface,
  });`

and now it is able to identify the files, but got this error

```
{
  err: MigrationError: Migration test-migration.js (up) failed: Original error: Unexpected token 'export'
      at /Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/node_modules/.pnpm/umzug@3.2.1/node_modules/umzug/lib/umzug.js:152:27
      at async Umzug.runCommand (/Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/node_modules/.pnpm/umzug@3.2.1/node_modules/umzug/lib/umzug.js:107:20)
      at async setup_setup (/Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/build/bundle.js:3219:46)
      at async setupDB (/Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/build/bundle.js:3223:611) {
    cause: /Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/node_modules/.pnpm/file+..+bhadra-build-js-config/node_modules/bhadra-build-js-config/src/db-config.js:3
    export const TABLES = {
    ^^^^^^
    
    SyntaxError: Unexpected token 'export'
        at compileFunction (<anonymous>)
        at Object.compileFunction (node:vm:352:18)
        at wrapSafe (node:internal/modules/cjs/loader:1033:15)
        at Module._compile (node:internal/modules/cjs/loader:1069:27)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/node_modules/.pnpm/file+..+bhadra-build-js-dynamodb-wrapper_openapi-types@12.1.3_request@2.88.2/node_modules/bhadra-build-js-db-wrapper/src/db/migrations/test-migration.js:6:20)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18),
    jse_cause: /Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/node_modules/.pnpm/file+..+bhadra-build-js-config/node_modules/bhadra-build-js-config/src/db-config.js:3
    export const TABLES = {
    ^^^^^^
    
    SyntaxError: Unexpected token 'export'
        at compileFunction (<anonymous>)
        at Object.compileFunction (node:vm:352:18)
        at wrapSafe (node:internal/modules/cjs/loader:1033:15)
        at Module._compile (node:internal/modules/cjs/loader:1069:27)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/node_modules/.pnpm/file+..+bhadra-build-js-dynamodb-wrapper_openapi-types@12.1.3_request@2.88.2/node_modules/bhadra-build-js-db-wrapper/src/db/migrations/test-migration.js:6:20)
        at Module._compile (node:internal/modules/cjs/loader:1105:14)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18),
    migration: {
      direction: 'up',
      name: 'test-migration.js',
      path: '/Users/pavan/Documents/GitHub/backflipt-platform/bhadra-build-backend/bhadra-build-js-platform-web-api/node_modules/.pnpm/file+..+bhadra-build-js-dynamodb-wrapper_openapi-types@12.1.3_request@2.88.2/node_modules/bhadra-build-js-db-wrapper/src/db/migrations/test-migration.js',
      context: [DynamoDBClient]
    }
  }
}
```

test-migration.js file code

```
const {
  PutItemCommand,
  DeleteItemCommand,
  GetItemCommand,
} = require("@aws-sdk/client-dynamodb");
const { TABLES } = require("config/src/db-config");

async function up({ context: queryInterface }) {
  const putItemCommand = new PutItemCommand({
    TableName: TABLES.USERS,
    Item: {
       name: 'test-user',
       id: '5f439079be375d4bed15c98e',
      },
    },
  });
  await queryInterface.send(putItemCommand);
}

async function down({ context: queryInterface }) {
  const deleteItemCommand = new DeleteItemCommand({
    TableName: TABLES.USERS,
    Key: {
      id: { S: "5f439079be375d4bed15c98e" },
    },
  });
  await queryInterface.send(deleteItemCommand);
}

module.exports = { up, down };
```
I am naive to bundling related stuff. can somebody please help in identifying this issue and also can this issue be solved with node.__dirname set to false in webpack config as well?</div>

**Comment by mmkal** [comment]
I'll reply on the discussion - closing this.
