### ISSUE TITLE
Trying to run tests gives an error

### ISSUE THREAD

**Issue by tremby** [sequelize/umzug#65]
When running `npm run test` I get this:

```
> umzug@1.9.1 test /home/bjn/src/umzug
> gulp

module.js:341
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/bjn/src/umzug/node_modules/gulp-jshint/src/extract.js:1:79)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17
```

**Comment by jukkah** [comment]
Hmm... I haven't seen this before. Tested just a moment ago with current master and sequelize@2.0.0. It seems the problem is in gulp-jshint and/or jshint not in umzug itself.

**Comment by tremby** [comment]
You get the same error?

**Comment by jukkah** [comment]
No. It worked fine.

**Comment by jukkah** [comment]
I have gulp-jshint@2.0.0 and jshint@2.9.1.

**Comment by tremby** [comment]
Am I supposed to have installed jshint globally?

**Comment by tremby** [comment]
Tests run fine if I npm install jshint. It's a missing dependency.

**Comment by jukkah** [comment]
Have you tried `npm install`? It seems gulp-jshint is not installed correctly, and this should fix it.

**Comment by tremby** [comment]
Of course I ran npm install. See my comment on the PR diff.
